defaults:
  - base_model

model_type: matnet
embedding_dim: 256
num_mhsa_layers: 4
ms_hidden_dim: 16

encoder_features:
  shelf:
    - loc
  item:
    - items_ohe_rand
    - demand_cvec

encoder_context_features: [] 

decoder_context_features:
  shelf:
    - remaining_load
  item:
    - remaining_load

decoder_dynamic_features:
  shelf: []
  item:
    - demand_w_dummy_cvec
  edge:
    - taken_units_w_depot_and_dummy_cvec