# @package _global_
defaults:
  - _self_
  - base_instance@instance

instance:
  num_shelves: 10
  num_skus: 6
  num_storage_locations: 20

train:
  batch_size: 512
  batch_size_valid: 1024
  max_grad_norm: 1.0
